full explicit remove memset
SegmentLinking/TrackLooper pull request #1
Opened 2020-11-04 17:20 UTC by tresreid

removed the memset for the full explicit case. Doesn't seem to affect objects further down the line. tested by running minidoublets with full explicit and segments with unified. same output as when running minidoublets in unified memory. 
Also removed cudaFree for temp objects. 
Fixes all issues raised by cuda-memcheck

2020-11-04 19:10 UTC, beiwang2003 reviewed
cudaFree should be there to make sure that things are deleted properly. If debugger compliant about anything related to cudaFree, it is likely that we have bugs in other places. If we remove memset, where the nMDs array being initialized then? We may see correct results now because the compiler tries to initialize it to zero. How about in the case the compiler choose not to initialize the allocated memory by default? 

I've tried the case w/o -DFull_Explicit option, cuda-memcheck issues errors at cudaFree call. If we switch to all unified memory (removing MEMFLAGS), everything runs normal and no errors in cuda-memcheck. 

I think there is a bug somewhere in the explicit memory implementation.

2020-11-05 15:56 UTC, beiwang2003 requested changes
ok bugs are identified. cudaMallocHost should pair with cudaFreeHost (but not cudaFree)

2020-11-05 16:00 UTC, beiwang2003 requested changes
Again, removing "cudamemset" is not the right way of fixing the issue. cudamemset takes the first argument as pointer to device address (*), but not (**). Try to modify how the first argument is passing to the function. That will fix that issue.

2020-11-05 18:41 UTC, tresreid commented
I've made the changes as @beiwang2003 has suggested

2020-11-05 18:46 UTC, beiwang2003 approved these changes

2020-11-05 19:21 UTC, beiwang2003 commented
merge to PR

2020-11-09 15:32 UTC, merged